#version: '3.4'

#services:
#  Tesseract.Api:
#    image: ${DOCKER_REGISTRY-}Tesseract.Api
#    build:
#      context: .
#      dockerfile: Tesseract.Api/Dockerfile

version: "3.4"

services:
  Tesseract.Api:
    container_name: Tesseract.Api
    image: Tesseract.Api
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile